name: Build Arduino Project

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: latest

      - name: Install Arduino AVR core
        run: arduino-cli core install arduino:avr

      - name: Compile Blinking Project
        run: |
          arduino-cli compile --fqbn arduino:avr:uno src/blinking
